### ISSUE TITLE
Stops snippet expansion if current word is the same as snippet prefix

### ISSUE THREAD

**Issue by robballou** [atom/autocomplete-snippets#16]
In cases where you have two snippets with prefixes like `dpm` and `dpmf` you cannot expand `dpm` because autocomplete will expand `dpmf`. As you start typing this, both snippets appear, but if you have typed `dpm` then only `dpmf` is shown in autocomplete. Subsequently if you hit tab then autocomplete takes over and expands `dpmf`.
## Reproduce

Snippets:

```
'.source.php':
  'dpm':
    'prefix': 'dpm'
    'body': 'dpm($1)'
  'dpmf':
    'prefix': 'dpmf'
    'body': 'dpmf($1)'
```

Open a PHP file, add the opening `<?php` tag then try to expand the dpm snippet.

**Comment by robballou** [comment]
This still seems to be the case (or is again):
![screenshot 2015-01-19 15 30 03](https://cloud.githubusercontent.com/assets/46527/5808926/1ff92096-9ff0-11e4-8f3f-088d15367678.png)

`pf` is a snippet, but to expand it I need to `ESC` and then tab.

**Comment by joefitzgerald** [comment]
Change your autocomplete-plus keybinding to `enter` instead of tab. This will fix the behavior you're seeing.

**Comment by robballou** [comment]
Yeah, I think that fixes the flow issue for this, thanks! I think in general I'm not seeing some snippets which doesn't fit under this issue :)

**Comment by joefitzgerald** [comment]
That is #22...
