### ISSUE TITLE
Snippets do not appear in autocomplete suggestions

### ISSUE THREAD

**Issue by robotgoblin** [atom/autocomplete-snippets#30]
When typing the beginning of a snippet (tried both the prefix and the actual snippet content) no suggestion appears for autocompletion.

For example, I've added the following snippet:

    '.source.cpp, .source.c':
        'Dummy Text':
            'prefix': 'dummy'
            'body': 'DummyText'

When typing `du`, `dum`, `dumm` or `dummy` no suggestions appear. However, when I type `dummy` and press Tab, the snippet is autocompleted with "DummyText" even though there was no suggestion shown.

*autocomplete-plus* does show the usual suggestions though, for example in a file with `int myNamedVar = 10;` typing `my` immediately shows the suggestions box with `myNamedVar` in.

**Comment by lmartins** [comment]
Having this exact same problem.

**Comment by jordanbtucker** [comment]
I'm having this problem, except only the last snippet in my snippets.cson is showing up.

**Comment by jordanbtucker** [comment]
This looks to be an issue with atom rather than autocomplete-snippets, since `atom.config.get('snippets')` is not returning all user defined snippets.

**Comment by jordanbtucker** [comment]
I figured out my issue, but I'm not sure if it's the same one you're having. This is what I had in my snippets.cson:

```cson
'.text.html.basic':
  'Spacebars If':
    'prefix': 'sif'
    'body': '{{#if $1}}\n$2\n{{/if}}'

'.text.html.basic':
  'Spacebars Each':
    'prefix': 'seach'
    'body': '{{#each $1}}\n$2\n{{/each}}'
```

Converting that to JSON would reveal that I'm setting the value of key `.text.html.basic` twice with the second one over writing the first.

```json
{
  ".text.html.basic": {"Spacebars If": {...}},
  ".text.html.basic": {"Spacebars Each": {...}}
}
```

It works after changing it to:

```cson
'.text.html.basic':

  'Spacebars If':
    'prefix': 'sif'
    'body': '{{#if $1}}\n$2\n{{/if}}'

  'Spacebars Each':
    'prefix': 'seach'
    'body': '{{#each $1}}\n$2\n{{/each}}'
```

**Comment by benogle** [comment]
Still an issue?

**Comment by benogle** [comment]
Closing as this seems to be resolved

**Comment by tunnckoCore** [comment]
Incidentally i needed to reinstall my dev setup machine and now I'm doing everything from scratch... and it seems it not work. I have my own package with pretty good snippets and installs. Also tried to install other and they don't appear too. Tried to quit and relaunch Atom - still the same, autocompletion suggests only the built-in snippets.
