### ISSUE TITLE
Sort comparator does not work

### ISSUE THREAD

**Issue by jeancroy** [atom/autocomplete-snippets#61]
The comparator looks like [this](https://github.com/atom/autocomplete-snippets/blob/master/lib/snippets-provider.coffee#L46)

````
ascendingPrefixComparator = (a, b) -> a.prefix  - b.prefix
````

However those prefixes are strings and  `"ab" - "xy"` results in `NaN`

**Comment by benogle** [comment]
You're right, we should use `<; >` etc.
