### ISSUE TITLE
how to use this package?

### ISSUE THREAD

**Issue by xh3b4sd** [atom/autocomplete-snippets#76]
I am new to Atom. I checked this package but I have no idea how it works and how I can make use of it. The readme also does not help that much. Where do snippets come from? Where are they going to? How is the completion invoked?

**Comment by Ben3eeE** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll be able to find answers faster.

**Comment by xh3b4sd** [comment]
Thank you for the response. I think one or two sentences in the `README.md` would save everybody some time. This is the package I am interested in. Why do I need to check some message board to get information about how to use a specific package? That does not make that much sense to me.

**Comment by Ben3eeE** [comment]
Thank you for your feedback on the readme for this package :bowing_man:. Improving the readme is an actionable issue and something that you can post here. I will be sure to pass this feedback along.

The [Atom Flight Manual](http://flight-manual.atom.io) has a great section on [snippets](http://flight-manual.atom.io/using-atom/sections/snippets/). This package adds snippets to the [autocomplete](http://flight-manual.atom.io/using-atom/sections/autocomplete/).
