### ISSUE TITLE
Languages not included in core

### ISSUE THREAD

**Issue by edubkendo** [atom/autocomplete-snippets#8]
Files of Rust syntax, even with the Rust language package installed were not getting snippets. It looks like, at the time autocomplete-snippets loads, the grammars not included in core have not yet been loaded up.  I was able to fix it locally with:

```coffeescript
  initialize: ->
    @snippetsLoader = new SnippetsLoader @editor
    @snippetsLoader.loadAll (@snippets) =>
      # Turn snippet into array
      snippets = []
      for key, val of @snippets
        val.label = key
        snippets.push val
      @snippets = snippets

    @editor.on "grammar-changed", =>
      @snippetsLoader.loadAll (@snippets) =>
        # Turn snippet into array
        snippets = []
        for key, val of @snippets
          val.label = key
          snippets.push val
        @snippets = snippets
```

I suspected (but did not test) that if I didn't duplicate it like that, those files whose snippets were already loaded initially, I believe languages from core, would never get the `grammar-changed` event. This is a very ugly solution. Of course factoring some of that out into a function would help but its still a kludge. That's why I didn't make it a pull-request.  Hopefully it points you in the right direction though.

**Comment by kevinsawicki** [comment]
I don't think this is still an issue given how this package now reads snippets from the config, closing this out.
