### ISSUE TITLE
Snippets not showing up in YAML Files

### ISSUE THREAD

**Issue by MCStreetguy** [atom/autocomplete-snippets#87]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When in a .yaml file, snippets are not available through autocompletion.
(This may occur in other syntaxes too)

### Steps to Reproduce

1. Create a snippet with scope '.source.yaml'
2. Try to use it in a .yaml file

**Expected behavior:** I get suggestions for snippets and may insert them.

**Actual behavior:** I get suggestions for variables and constants, but not snippets.

**Reproduces how often:** Always

### Versions

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1

Running on macOS Sierra, Version 10.12.6 (16G29) 

### Additional Information

This was already mentioned on Atom Discuss: https://discuss.atom.io/t/yaml-snippet-not-triggering-after-a-field-name/34856/4

**Comment by 50Wliu** [comment]
The snippet will still work if you press <kbd>tab</kbd>, autocomplete-snippets just won't visually hint that there is a snippet available.  This is because the majority of YAML has a (semantically correct) `.string` scope, which per the Discuss thread prevents autocomplete-snippets from displaying the snippet.
