### ISSUE TITLE
Allow avoiding certain words - feature request

### ISSUE THREAD

**Issue by ppazos** [atom/autocomplete-snippets#95]
### Description

This plugin doesn't have any configuration options.

When writing text for HTML files, is really annoying that the snippet suggest appears on every single character typed. Even more when I need to press enter to get to a new line, I need to press ESC to close the snippet suggestion then enter to go to the next line.

### Steps to Reproduce

1. Just use the plugin normally and you will see the behavior I described.

**Expected behavior:**

For stuff like "the", "a", "in", "at", etc. I would love to turn the snippet suggestion off. Or even launch the suggestion when I want a suggestion. Other editors launch suggestions after typing some characters and then press CRTL + SPACE. I think this is a more elegant approach than just suggest on every single key stroke. In my case, I want a snipped inserted when I type only 0.1% of the type.

**Actual behavior:**

Snippet appears on every single key stroke.

**Reproduces how often:**

Always, is how the plugin was designed I think.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 1.9.1

Linux Mint 17.3

**Comment by rsese** [comment]
Thanks for the suggestion - I think there are a few existing settings that might help in some ways but first, can you share more details of this behavior you describe?

>  the snippet suggest appears on every single character typed. 

If you can share an example step by step flow and a GIF/screencast, that would be helpful.

Also:

> Atom : 1.18.0

The current stable release version of Atom is 1.29, can you update in case some of the behavior you're describing has changed over time?

**Comment by ppazos** [comment]
@rsese please check https://www.youtube.com/watch?v=jgfLziwK-30

**Comment by Aerijo** [comment]
@ppazos Maybe setting the keybinding to <kbd>tab</kbd> is what you want? This can be done in the pckage settings.

Alternatively, if you still want to use <kbd>ctrl + enter</kbd>, you can add this to your `keymaps.cson` file (if the `atom-text-editor` key is already there, just add the second line to it & ensure correct indentation).
```
"atom-text-editor":
  "ctrl-enter": "autocomplete-plus:confirm"
```

I don't know if there's an easy way to remove the default keybindings entirely, but setting it to `<kbd>kbd</kbd> should be much less invasive.

**Comment by rsese** [comment]
👍 on @Aerijo's suggestions.

Also about this:

> the snippet suggest appears on every single character typed.

It looks like there's an open issue about how snippets don't respect the `Minimum World Length` setting:

https://github.com/atom/autocomplete-snippets/issues/75

Additionally:

> Other editors launch suggestions after typing some characters and then press CRTL + SPACE. I think this is a more elegant approach than just suggest on every single key stroke. 

You can't do this for just snippets but you can for all autocompletion with the `Show Suggestions On Keystroke` setting - if you disable this setting, you can manually show autocomplete suggestions after typing some characters with the `Autocomplete Plus: Activate` command.

Also it sounds like snippets in general aren't useful for you?  If that's the case, you can also disable the `autocomplete-snippets` package.

**Comment by ppazos** [comment]
@Aerijo I'm a little lost about the atom terminology, what's a keybinding? Is that the key that triggers the suggestion?

I'm not sure about tab, what if I need to enter a tab on my code?

I checked the autocomplete-plus config and on keybindings I have ctrl+space for autocomplete-plus:activate but ctrl+space does nothing. Also have escape for autocomplete-plus:cancel and that works OK (hides the suggestions).

**Comment by ppazos** [comment]
@rsese Thanks for the input, snippets are useful, but want to trigger it when I need them, not on every single key stroke. That is because I know when and where to place snippets but the plugin doesn't :)

**Comment by rsese** [comment]
> snippets are useful, but want to trigger it when I need them, not on every single key stroke.

Does disabling the `Show Suggestions On Keystroke` setting I described above help?
